const {
  EXECUTION_STATES,
  TERMINAL_STATES,
  AGENT_TO_STATE,
} = require("./constants");

const ALLOWED = {
  [EXECUTION_STATES.QUEUED]: [
    EXECUTION_STATES.PLANNING,
    EXECUTION_STATES.CANCELLED,
    EXECUTION_STATES.FAILED,
  ],
  [EXECUTION_STATES.PLANNING]: [
    EXECUTION_STATES.RESEARCHING,
    EXECUTION_STATES.ARCHITECTING,
    EXECUTION_STATES.CODING,
    EXECUTION_STATES.TESTING,
    EXECUTION_STATES.REVIEWING,
    EXECUTION_STATES.COMPLETED,
    EXECUTION_STATES.FAILED,
    EXECUTION_STATES.CANCELLED,
  ],
  [EXECUTION_STATES.RESEARCHING]: [
    EXECUTION_STATES.ARCHITECTING,
    EXECUTION_STATES.CODING,
    EXECUTION_STATES.TESTING,
    EXECUTION_STATES.REVIEWING,
    EXECUTION_STATES.FIXING,
    EXECUTION_STATES.COMPLETED,
    EXECUTION_STATES.FAILED,
    EXECUTION_STATES.CANCELLED,
  ],
  [EXECUTION_STATES.ARCHITECTING]: [
    EXECUTION_STATES.CODING,
    EXECUTION_STATES.TESTING,
    EXECUTION_STATES.REVIEWING,
    EXECUTION_STATES.RESEARCHING,
    EXECUTION_STATES.FIXING,
    EXECUTION_STATES.COMPLETED,
    EXECUTION_STATES.FAILED,
    EXECUTION_STATES.CANCELLED,
  ],
  [EXECUTION_STATES.CODING]: [
    EXECUTION_STATES.TESTING,
    EXECUTION_STATES.REVIEWING,
    EXECUTION_STATES.FIXING,
    EXECUTION_STATES.CODING,
    EXECUTION_STATES.COMPLETED,
    EXECUTION_STATES.FAILED,
    EXECUTION_STATES.CANCELLED,
  ],
  [EXECUTION_STATES.TESTING]: [
    EXECUTION_STATES.REVIEWING,
    EXECUTION_STATES.FIXING,
    EXECUTION_STATES.CODING,
    EXECUTION_STATES.COMPLETED,
    EXECUTION_STATES.FAILED,
    EXECUTION_STATES.CANCELLED,
  ],
  [EXECUTION_STATES.REVIEWING]: [
    EXECUTION_STATES.FIXING,
    EXECUTION_STATES.CODING,
    EXECUTION_STATES.TESTING,
    EXECUTION_STATES.COMPLETED,
    EXECUTION_STATES.FAILED,
    EXECUTION_STATES.CANCELLED,
  ],
  [EXECUTION_STATES.FIXING]: [
    EXECUTION_STATES.CODING,
    EXECUTION_STATES.TESTING,
    EXECUTION_STATES.REVIEWING,
    EXECUTION_STATES.COMPLETED,
    EXECUTION_STATES.FAILED,
    EXECUTION_STATES.CANCELLED,
  ],
  [EXECUTION_STATES.COMPLETED]: [],
  [EXECUTION_STATES.FAILED]: [EXECUTION_STATES.QUEUED, EXECUTION_STATES.PLANNING],
  [EXECUTION_STATES.CANCELLED]: [],
};

function canTransition(from, to) {
  if (!from) return true;
  if (from === to) return true;
  const allowed = ALLOWED[from] || [];
  return allowed.includes(to);
}

function assertTransition(from, to) {
  if (!canTransition(from, to)) {
    const err = new Error(`Invalid state transition: ${from} → ${to}`);
    err.code = "INVALID_STATE_TRANSITION";
    throw err;
  }
}

function stateForAgent(agentType) {
  return AGENT_TO_STATE[agentType] || null;
}

function isTerminal(state) {
  return TERMINAL_STATES.has(state);
}

module.exports = {
  canTransition,
  assertTransition,
  stateForAgent,
  isTerminal,
  ALLOWED,
};
