const coordinatorAgent = require("../agents/coordinator.agent");
const projectRepository = require("../repositories/project.repository");

const STAGES = [
  "Planner",
  "Research",
  "Architect",
  "Coding",
  "Testing",
  "Reviewer",
  "Completed",
];

const FRAMEWORK_TEMPLATES = {
  react: (name, description) => [
    {
      name: "src",
      path: "/src",
      isFolder: true,
      content: "",
    },
    {
      name: "App.jsx",
      path: "/src/App.jsx",
      parentPath: "/src",
      content: `import { useState } from "react";

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <div style={{
      minHeight: "100vh",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      background: "linear-gradient(145deg, #0F172A 0%, #1B2748 50%, #24335F 100%)",
      color: "#F1F5F9",
      fontFamily: "Segoe UI, system-ui, sans-serif",
      padding: 24,
    }}>
      <h1 style={{
        fontSize: 32,
        fontWeight: 800,
        marginBottom: 8,
        background: "linear-gradient(90deg, #F15B42, #F49CC4)",
        WebkitBackgroundClip: "text",
        WebkitTextFillColor: "transparent",
      }}>${name}</h1>
      <p style={{ color: "#94A3B8", marginBottom: 24, maxWidth: 420, textAlign: "center" }}>
        ${description || "OpenClaw workspace project"}
      </p>
      <button
        onClick={() => setCount((c) => c + 1)}
        style={{
          padding: "12px 24px",
          background: "#F15B42",
          color: "#fff",
          border: "none",
          borderRadius: 12,
          fontWeight: 700,
          cursor: "pointer",
          boxShadow: "0 8px 24px rgba(241,91,66,0.3)",
        }}
      >
        Count: {count}
      </button>
    </div>
  );
}
`,
    },
    {
      name: "main.jsx",
      path: "/src/main.jsx",
      parentPath: "/src",
      content: `import { createRoot } from "react-dom/client";
import App from "./App.jsx";

createRoot(document.getElementById("root")).render(<App />);
`,
    },
    {
      name: "index.html",
      path: "/index.html",
      content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name}</title>
    <script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  </head>
  <body style="margin:0;background:#0F172A;">
    <div id="root"></div>
    <script type="text/babel" data-presets="react">
      function App() {
        const [count, setCount] = React.useState(0);
        return (
          <div style={{minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",background:"linear-gradient(145deg,#0F172A,#1B2748)",color:"#F1F5F9",fontFamily:"Segoe UI,sans-serif",padding:24}}>
            <h1 style={{fontSize:32,fontWeight:800,background:"linear-gradient(90deg,#F15B42,#F49CC4)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>${name}</h1>
            <p style={{color:"#94A3B8",marginBottom:24}}>${(description || "OpenClaw workspace").replace(/`/g, "'")}</p>
            <button onClick={() => setCount(c => c + 1)} style={{padding:"12px 24px",background:"#F15B42",color:"#fff",border:"none",borderRadius:12,fontWeight:700,cursor:"pointer"}}>Count: {count}</button>
          </div>
        );
      }
      ReactDOM.createRoot(document.getElementById("root")).render(<App />);
    </script>
  </body>
</html>
`,
    },
    {
      name: "package.json",
      path: "/package.json",
      content: JSON.stringify(
        {
          name: name.toLowerCase().replace(/\s+/g, "-"),
          private: true,
          version: "0.0.1",
          type: "module",
          scripts: { dev: "vite", build: "vite build" },
          dependencies: {
            react: "^18.3.1",
            "react-dom": "^18.3.1",
          },
        },
        null,
        2
      ),
    },
    {
      name: "README.md",
      path: "/README.md",
      content: `# ${name}\n\n${description || "Generated by OpenClaw Workspace"}\n\nFramework: React\n`,
    },
  ],
  html: (name, description) => [
    {
      name: "index.html",
      path: "/index.html",
      content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <main class="hero">
    <h1>${name}</h1>
    <p>${description || "OpenClaw HTML workspace"}</p>
    <button id="cta">Get Started</button>
  </main>
  <script src="app.js"><\/script>
</body>
</html>
`,
    },
    {
      name: "styles.css",
      path: "/styles.css",
      content: `* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  min-height: 100vh;
  display: grid;
  place-items: center;
  background: linear-gradient(145deg, #0F172A, #1B2748 50%, #24335F);
  color: #F1F5F9;
  font-family: "Segoe UI", system-ui, sans-serif;
}
.hero { text-align: center; padding: 2rem; }
h1 {
  font-size: 2.5rem;
  background: linear-gradient(90deg, #F15B42, #F49CC4);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  margin-bottom: 0.75rem;
}
p { color: #94A3B8; margin-bottom: 1.5rem; max-width: 28rem; }
button {
  background: #F15B42;
  color: white;
  border: none;
  padding: 0.75rem 1.5rem;
  border-radius: 12px;
  font-weight: 700;
  cursor: pointer;
  box-shadow: 0 8px 24px rgba(241,91,66,0.3);
}
button:hover { background: #e04a31; }
`,
    },
    {
      name: "app.js",
      path: "/app.js",
      content: `document.getElementById("cta")?.addEventListener("click", () => {
  alert("${name} is ready — built with OpenClaw.");
});
`,
    },
    {
      name: "README.md",
      path: "/README.md",
      content: `# ${name}\n\n${description || "Generated by OpenClaw Workspace"}\n\nFramework: HTML\n`,
    },
  ],
  vanilla: (name, description) => [
    {
      name: "index.html",
      path: "/index.html",
      content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${name}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <div id="app"></div>
  <script type="module" src="main.js"><\/script>
</body>
</html>
`,
    },
    {
      name: "main.js",
      path: "/main.js",
      content: `const app = document.getElementById("app");
app.innerHTML = \`
  <h1>${name}</h1>
  <p>${description || "Vanilla JS OpenClaw project"}</p>
  <button id="btn">Click me</button>
\`;
document.getElementById("btn").addEventListener("click", () => {
  console.log("OpenClaw workspace ready");
});
`,
    },
    {
      name: "style.css",
      path: "/style.css",
      content: `body {
  margin: 0;
  min-height: 100vh;
  display: grid;
  place-items: center;
  background: #0F172A;
  color: #F1F5F9;
  font-family: system-ui, sans-serif;
  text-align: center;
}
h1 { color: #F15B42; }
button {
  margin-top: 1rem;
  padding: 0.75rem 1.25rem;
  background: #7CAADC;
  border: none;
  border-radius: 8px;
  color: #0F172A;
  font-weight: 700;
  cursor: pointer;
}
`,
    },
    {
      name: "README.md",
      path: "/README.md",
      content: `# ${name}\n\n${description || "Generated by OpenClaw Workspace"}\n\nFramework: Vanilla JS\n`,
    },
  ],
};

async function seedTemplateFiles(projectId, framework, name, description) {
  const factory = FRAMEWORK_TEMPLATES[framework] || FRAMEWORK_TEMPLATES.react;
  const entries = factory(name, description);
  const pathToId = {};

  for (const entry of entries) {
    const parentId = entry.parentPath ? pathToId[entry.parentPath] || null : null;
    const file = await projectRepository.createFile(projectId, {
      name: entry.name,
      path: entry.path,
      content: entry.content,
      isFolder: entry.isFolder || false,
      parentId,
    });
    pathToId[entry.path] = file.id;
  }

  return pathToId;
}

function makeStage(name, status = "pending", summary = null) {
  return {
    name,
    status,
    summary,
    startedAt: null,
    completedAt: null,
  };
}

async function runGenerationPipeline(project, userId) {
  const stages = STAGES.map((name) => makeStage(name));
  let execution = await projectRepository.createExecution(project.id, {
    status: "running",
    currentStage: "Planner",
    stages,
  });

  await projectRepository.update(project.id, userId, { status: "building" });
  await projectRepository.createLog(project.id, {
    level: "info",
    source: "ai",
    message: `Generation started for "${project.name}" (${project.framework})`,
  });

  const stageSummaries = {
    Planner: `Planned architecture for ${project.framework} project "${project.name}".`,
    Research: `Researched ${project.framework} patterns and OpenClaw conventions.`,
    Architect: `Designed folder structure and entry points for ${project.name}.`,
    Coding: `Generated starter files for ${project.framework}.`,
    Testing: `Validated file tree and entry points.`,
    Reviewer: `Reviewed generated scaffold for consistency.`,
    Completed: `Project "${project.name}" is ready in the workspace.`,
  };

  for (let i = 0; i < STAGES.length; i++) {
    const stageName = STAGES[i];
    stages[i] = {
      ...stages[i],
      status: "running",
      startedAt: new Date().toISOString(),
      summary: null,
    };

    execution = await projectRepository.updateExecution(execution.id, {
      currentStage: stageName,
      stages,
      status: stageName === "Completed" ? "completed" : "running",
    });

    await projectRepository.createLog(project.id, {
      level: "info",
      source: "ai",
      message: `[${stageName}] Running…`,
    });

    if (stageName === "Coding") {
      await seedTemplateFiles(
        project.id,
        project.framework,
        project.name,
        project.description
      );
    }

    // Optional AI reasoning — fall back to local summary if provider fails
    let summary = stageSummaries[stageName];
    if (stageName === "Planner" || stageName === "Architect") {
      try {
        const aiText = await coordinatorAgent(
          `In 2 short sentences, summarize the ${stageName.toLowerCase()} stage for an OpenClaw ${project.framework} project named "${project.name}". Description: ${project.description || "none"}. Be concrete about files/structure.`,
          "You are an OpenClaw workspace architect. Be concise.",
          "",
          "",
          "",
          "",
          { temperature: 0.3 }
        );
        if (aiText && !String(aiText).includes("quota exceeded") && !String(aiText).includes("No AI provider")) {
          summary = String(aiText).slice(0, 500);
        }
      } catch {
        // keep local summary
      }
    }

    stages[i] = {
      ...stages[i],
      status: "completed",
      completedAt: new Date().toISOString(),
      summary,
    };

    await projectRepository.updateExecution(execution.id, {
      stages,
      summary: stageName === "Completed" ? summary : execution.summary,
      status: stageName === "Completed" ? "completed" : "running",
      currentStage: stageName === "Completed" ? "Completed" : STAGES[i + 1],
    });

    await projectRepository.createLog(project.id, {
      level: "info",
      source: "ai",
      message: `[${stageName}] Completed — ${summary}`,
    });
  }

  await projectRepository.update(project.id, userId, { status: "active" });
  const populated = await projectRepository.findById(project.id, userId);
  try {
    const fsWorkspace = require("./fs-workspace.service");
    await fsWorkspace.syncProjectToDisk(userId, populated);
  } catch (e) {
    console.warn("workspace sync:", e.message);
  }
  return populated;
}

async function runAiEdit({ projectId, userId, fileId, selection, action, instruction }) {
  const project = await projectRepository.findById(projectId, userId);
  if (!project) throw new Error("Project not found");

  const file = project.files.find((f) => f.id === fileId);
  if (!file || file.isFolder) throw new Error("File not found");

  const stages = STAGES.map((name) => makeStage(name));
  let execution = await projectRepository.createExecution(projectId, {
    status: "running",
    currentStage: "Planner",
    stages,
  });

  await projectRepository.createLog(projectId, {
    level: "info",
    source: "ai",
    message: `AI edit (${action}) on ${file.path}`,
  });

  const actionPrompt = {
    improve: "Improve code quality and clarity",
    optimize: "Optimize for performance and readability",
    explain: "Explain the code (return the original code unchanged, put explanation in comments above)",
    refactor: "Refactor for maintainability without changing behavior",
    fix: "Fix bugs and edge cases",
  }[action] || "Improve the code";

  const targetCode = selection || file.content;

  for (let i = 0; i < STAGES.length; i++) {
    const stageName = STAGES[i];
    stages[i] = {
      ...stages[i],
      status: "running",
      startedAt: new Date().toISOString(),
    };
    await projectRepository.updateExecution(execution.id, {
      currentStage: stageName,
      stages,
    });

    let summary = `${stageName} for ${action} on ${file.name}`;
    let afterContent = null;

    if (stageName === "Coding") {
      try {
        const result = await coordinatorAgent(
          `You are editing a file in an OpenClaw IDE.
Action: ${actionPrompt}
${instruction ? `Extra instruction: ${instruction}` : ""}
File: ${file.path}
Language inferred from extension.

Return ONLY the full replacement code for the selected region (or whole file if no selection). No markdown fences.

CODE:
\`\`\`
${targetCode}
\`\`\`
`,
          "Return only code. No explanations.",
          "",
          "",
          "",
          "",
          { temperature: 0.2 }
        );

        afterContent = String(result || "")
          .replace(/^```[\w]*\n?/m, "")
          .replace(/\n?```$/m, "")
          .trim();

        if (!afterContent || afterContent.includes("quota exceeded")) {
          throw new Error("AI unavailable");
        }
        summary = `Generated ${action} changes for ${file.name}`;
      } catch (err) {
        // Deterministic local transforms when AI is unavailable
        if (action === "explain") {
          afterContent = `/* OpenClaw: ${action} — ${instruction || "explanation"} */\n${targetCode}`;
        } else if (action === "optimize" || action === "improve" || action === "refactor") {
          afterContent = targetCode
            .replace(/\s+$/gm, "")
            .replace(/\n{3,}/g, "\n\n");
          if (!afterContent.includes("OpenClaw")) {
            afterContent = `/* OpenClaw ${action} */\n${afterContent}`;
          }
        } else if (action === "fix") {
          afterContent = targetCode.replace(/console\.log\(/g, "console.debug(");
          if (afterContent === targetCode) {
            afterContent = `/* OpenClaw fix pass */\n${targetCode}`;
          }
        } else {
          afterContent = `/* OpenClaw ${action} */\n${targetCode}`;
        }
        summary = `Applied local ${action} transform (${err.message})`;
        await projectRepository.createLog(projectId, {
          level: "warning",
          source: "ai",
          message: `AI provider fallback: ${err.message}`,
        });
      }

      const before = file.content;
      let after = before;
      if (selection && before.includes(selection)) {
        after = before.replace(selection, afterContent);
      } else {
        after = afterContent;
      }

      await projectRepository.createDiff(projectId, {
        fileId: file.id,
        filePath: file.path,
        before,
        after,
        reason: `${action}${instruction ? `: ${instruction}` : ""}`,
      });
    }

    stages[i] = {
      ...stages[i],
      status: "completed",
      completedAt: new Date().toISOString(),
      summary,
    };
    await projectRepository.updateExecution(execution.id, {
      stages,
      status: stageName === "Completed" ? "completed" : "running",
      currentStage: stageName === "Completed" ? "Completed" : STAGES[i + 1],
      summary: stageName === "Completed" ? summary : undefined,
      tokensUsed: Math.ceil((targetCode.length + (summary || "").length) / 4) * (i + 1),
      promptTokens: Math.ceil(targetCode.length / 4),
      completionTokens: Math.ceil((summary || "").length / 4),
    });
  }

  await projectRepository.createLog(projectId, {
    level: "info",
    source: "ai",
    message: `AI edit complete — pending diff for ${file.path}`,
  });

  try {
    const fsWorkspace = require("./fs-workspace.service");
    const populated = await projectRepository.findById(projectId, userId);
    await fsWorkspace.syncProjectToDisk(userId, populated);
  } catch (e) {
    console.warn("workspace sync:", e.message);
  }

  return projectRepository.findById(projectId, userId);
}

module.exports = {
  STAGES,
  seedTemplateFiles,
  runGenerationPipeline,
  runAiEdit,
  FRAMEWORK_TEMPLATES,
};
