const { EXECUTION_STATUS, TERMINAL_EXECUTION } = require("../constants");

const TRANSITIONS = {
  [EXECUTION_STATUS.QUEUED]: [
    EXECUTION_STATUS.RUNNING,
    EXECUTION_STATUS.CANCELLED,
  ],
  [EXECUTION_STATUS.RUNNING]: [
    EXECUTION_STATUS.PAUSED,
    EXECUTION_STATUS.WAITING,
    EXECUTION_STATUS.AWAITING_APPROVAL,
    EXECUTION_STATUS.COMPLETED,
    EXECUTION_STATUS.FAILED,
    EXECUTION_STATUS.CANCELLED,
    EXECUTION_STATUS.TIMED_OUT,
  ],
  [EXECUTION_STATUS.PAUSED]: [
    EXECUTION_STATUS.RUNNING,
    EXECUTION_STATUS.CANCELLED,
  ],
  [EXECUTION_STATUS.WAITING]: [
    EXECUTION_STATUS.RUNNING,
    EXECUTION_STATUS.CANCELLED,
    EXECUTION_STATUS.TIMED_OUT,
    EXECUTION_STATUS.FAILED,
  ],
  [EXECUTION_STATUS.AWAITING_APPROVAL]: [
    EXECUTION_STATUS.RUNNING,
    EXECUTION_STATUS.CANCELLED,
    EXECUTION_STATUS.FAILED,
  ],
  [EXECUTION_STATUS.COMPLETED]: [],
  [EXECUTION_STATUS.FAILED]: [EXECUTION_STATUS.QUEUED, EXECUTION_STATUS.RUNNING],
  [EXECUTION_STATUS.CANCELLED]: [],
  [EXECUTION_STATUS.TIMED_OUT]: [EXECUTION_STATUS.QUEUED, EXECUTION_STATUS.RUNNING],
};

function canTransition(from, to) {
  return (TRANSITIONS[from] || []).includes(to);
}

function isTerminal(status) {
  return TERMINAL_EXECUTION.has(status);
}

function assertTransition(from, to) {
  if (!canTransition(from, to)) {
    throw Object.assign(new Error(`Invalid transition ${from} → ${to}`), {
      code: "INVALID_TRANSITION",
    });
  }
}

module.exports = {
  TRANSITIONS,
  canTransition,
  isTerminal,
  assertTransition,
};
